# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Test Automation Tutorials
tagline:          'learning simplified'
description:      'All these tutorials are scripted by Arulprasath.He also writes useful general articles for Engineering students at <a href="http://www.counsellingguru.com" target="_blank">CounsellingGuru.com</a>. You can contact us through our<a href="https://www.facebook.com/counsellingguruteam/" target="_blank">facebook page</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
