# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Test Automation Tutorials
tagline:          'Learning simplified'
description:      'These tutorials are written by Arulprasath. He is a professional trainer and test automation developer in India's largest IT exporter.'
url:              https://arulprasath36.github.io/
baseurl:          /

author:
  name:           'Arulprasath.R'
 

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Arulprasath36/TestAutomationExamples
