# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Selenium
tagline:          'learning simplified'
description:      'Tutorials are scripted by Arulprasath from <a href="http://www.counsellingguru.com" target="_blank">CounsellingGuru.com</a>. Contact us through <a href="https://www.facebook.com/counsellingguruteam/" target="_blank">facebook page</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
